version: '3.8'

services:
  postgres:
    image: postgres:15.2
    container_name: my_postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=StorageDB
    ports:
      - '5432:5432'